### ISSUE TITLE
Failing to make a PUT request with dbs3-client v.3.16.2000

### ISSUE THREAD

**Issue by amaltaro** [dmwm/DBSClient#16]
Yuyi,

I have a script that I've been using for the last many years, which allow me to change the status of a dataset and also all its files.
With all the WMAgents running now in Python3, I had to make some minor updates to it. However, there seem to have an inconsistency/issue with the dbs client itself, with the classic string vs byte objects.

Here's a snippet on how to reproduce (two problems actually), assuming that you have Python 3.8.2 (from COMP) and py3-dbs3-client 3.16.2000:
```
from dbs.apis.dbsClient import DbsApi
url = 'https://cmsweb-testbed.cern.ch/dbs/int/global/DBSWriter'
url = url.encode("utf-8")  # now we have a bytes object
dbsapi = DbsApi(url=url)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/srv/wmagent/v1.5.4.pre2/sw/slc7_amd64_gcc630/cms/py3-dbs3-client/3.16.2000/lib/python3.8/site-packages/dbs/apis/dbsClient.py", line 160, in __init__
    if url.find(":", 6) == -1:
TypeError: argument should be integer or bytes-like object, not 'str'
``` 

second problem comes up when we try to use `updateDatasetType` PUT API, e.g.:
```
>>> from dbs.apis.dbsClient import DbsApi
>>> url = 'https://cmsweb-testbed.cern.ch/dbs/int/global/DBSWriter'
>>> dataset = '/RelValMinBias_14TeV/CMSSW_12_0_0_pre6-120X_mcRun3_2021_realistic_v4-v1/GEN-SIM'
>>> status = 'VALID'
>>> dbsapi = DbsApi(url=url)
>>> dbsapi.updateDatasetType(dataset=dataset, dataset_access_type=status)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/srv/wmagent/v1.5.4.pre2/sw/slc7_amd64_gcc630/cms/py3-dbs3-client/3.16.2000/lib/python3.8/site-packages/dbs/apis/dbsClient.py", line 1647, in updateDatasetType
    return self.__callServer("datasets", params=kwargs, callmethod='PUT')
  File "/data/srv/wmagent/v1.5.4.pre2/sw/slc7_amd64_gcc630/cms/py3-dbs3-client/3.16.2000/lib/python3.8/site-packages/dbs/apis/dbsClient.py", line 200, in __callServer
    self.http_response = method_func(self.url, method, params, data, request_headers)
  File "/data/srv/wmagent/v1.5.4.pre2/sw/slc7_amd64_gcc630/cms/py3-dbs3-pycurl-client/3.16.2000/lib/python3.8/site-packages/RestClient/RestApi.py", line 43, in put
    http_request = HTTPRequest(method='PUT', url=url, api=api, params=params, data=data,
  File "/data/srv/wmagent/v1.5.4.pre2/sw/slc7_amd64_gcc630/cms/py3-dbs3-pycurl-client/3.16.2000/lib/python3.8/site-packages/RestClient/RequestHandling/HTTPRequest.py", line 38, in __init__
    data_fp = BytesIO(data)
TypeError: a bytes-like object is required, not 'str'
```

This is not affecting central production because we do not use this API, but it might affect Unified at some point.

PS.: In case you have a specific tool for this, would you mind setting this dataset `/RelValMinBias_14TeV/CMSSW_12_0_0_pre6-120X_mcRun3_2021_realistic_v4-v1/GEN-SIM` to VALID (and mark ALL its files to valid as well)? For some reason, its files were marked as invalid during the migration from prod/global to int/global

**Comment by amaltaro** [comment]
Indeed I can see it in PyPi: https://pypi.org/project/dbs3-client/
I will give it a try and update this issue with results. I could be wrong, but I think it will work out of the box for WMCore systems.

Thanks and have a restful vacation, Yuyi!

**Comment by yuyiguo** [comment]
Hi Alan,
Thanks for your good wishes. I do need a restful vacation.

Please see below query on dbs int db. There are seven files in the dataset `/RelValMinBias_14TeV/CMSSW_12_0_0_pre6-120X_mcRun3_2021_realistic_v4-v1/GEN-SIM `and all of them are valid. The dataset is valid too.

`select IS_DATASET_VALID , dataset_id from datasets where dataset='/RelValMinBias_14TeV/CMSSW_12_0_0_pre6-120X_mcRun3_2021_realistic_v4-v1/GEN-SIM';`

`1	14237791`

```
 select logical_file_name, IS_FILE_VALID, file_type from files f
 join file_data_types t on t.file_type_id=f.file_type_id 
  where dataset_id=14237791;
```

```
/store/relval/CMSSW_12_0_0_pre6/RelValMinBias_14TeV/GEN-SIM/120X_mcRun3_2021_realistic_v4-v1/00000/7475edf8-1e60-4cd0-a57c-4ef6611aa6e3.root	1	EDM
/store/relval/CMSSW_12_0_0_pre6/RelValMinBias_14TeV/GEN-SIM/120X_mcRun3_2021_realistic_v4-v1/00000/45ffacf4-9863-478d-af36-1f5624f08ecf.root	1	EDM
/store/relval/CMSSW_12_0_0_pre6/RelValMinBias_14TeV/GEN-SIM/120X_mcRun3_2021_realistic_v4-v1/00000/a602c821-a094-4e79-b494-cd4d8c0ac010.root	1	EDM
/store/relval/CMSSW_12_0_0_pre6/RelValMinBias_14TeV/GEN-SIM/120X_mcRun3_2021_realistic_v4-v1/00000/d362fce9-ea34-481a-a896-cd4b996b0f00.root	1	EDM
/store/relval/CMSSW_12_0_0_pre6/RelValMinBias_14TeV/GEN-SIM/120X_mcRun3_2021_realistic_v4-v1/00000/aee67840-3908-461b-bf3a-effe38e510bb.root	1	EDM
/store/relval/CMSSW_12_0_0_pre6/RelValMinBias_14TeV/GEN-SIM/120X_mcRun3_2021_realistic_v4-v1/00000/fc6ea615-085c-4d4a-8eae-5bf1c3a45078.root	1	EDM
/store/relval/CMSSW_12_0_0_pre6/RelValMinBias_14TeV/GEN-SIM/120X_mcRun3_2021_realistic_v4-v1/00000/f6145ee9-113a-487a-ad7f-664fa5c39a26.root	1	EDM
```

**Comment by yuyiguo** [comment]
Alan,
It is me again. I thought about that sometimes Imran configures DBS int server with the k8s database.  So I checked it. In deed, the files there were not valid. 
`select IS_DATASET_VALID , dataset_id from cms_dbs3_k8s_global_owner.datasets where dataset='/RelValMinBias_14TeV/CMSSW_12_0_0_pre6-120X_mcRun3_2021_realistic_v4-v1/GEN-SIM';`
 
1	    14187422

```
select logical_file_name, IS_FILE_VALID, file_type from cms_dbs3_k8s_global_owner.files f
 join cms_dbs3_k8s_global_owner.file_data_types t on t.file_type_id=f.file_type_id 
  where dataset_id=14187422;
```
```
/store/relval/CMSSW_12_0_0_pre6/RelValMinBias_14TeV/GEN-SIM/120X_mcRun3_2021_realistic_v4-v1/00000/f6145ee9-113a-487a-ad7f-664fa5c39a26.root	0	EDM
/store/relval/CMSSW_12_0_0_pre6/RelValMinBias_14TeV/GEN-SIM/120X_mcRun3_2021_realistic_v4-v1/00000/fc6ea615-085c-4d4a-8eae-5bf1c3a45078.root	0	EDM
/store/relval/CMSSW_12_0_0_pre6/RelValMinBias_14TeV/GEN-SIM/120X_mcRun3_2021_realistic_v4-v1/00000/aee67840-3908-461b-bf3a-effe38e510bb.root	0	EDM
/store/relval/CMSSW_12_0_0_pre6/RelValMinBias_14TeV/GEN-SIM/120X_mcRun3_2021_realistic_v4-v1/00000/d362fce9-ea34-481a-a896-cd4b996b0f00.root	0	EDM
/store/relval/CMSSW_12_0_0_pre6/RelValMinBias_14TeV/GEN-SIM/120X_mcRun3_2021_realistic_v4-v1/00000/a602c821-a094-4e79-b494-cd4d8c0ac010.root	0	EDM
/store/relval/CMSSW_12_0_0_pre6/RelValMinBias_14TeV/GEN-SIM/120X_mcRun3_2021_realistic_v4-v1/00000/45ffacf4-9863-478d-af36-1f5624f08ecf.root	0	EDM
/store/relval/CMSSW_12_0_0_pre6/RelValMinBias_14TeV/GEN-SIM/120X_mcRun3_2021_realistic_v4-v1/00000/7475edf8-1e60-4cd0-a57c-4ef6611aa6e3.root	0	EDM
 

```

```
update cms_dbs3_k8s_global_owner.files set is_file_valid=1 where dataset_id=14187422;
  
  commit;

```

```
select logical_file_name, IS_FILE_VALID, file_type from cms_dbs3_k8s_global_owner.files f
 join cms_dbs3_k8s_global_owner.file_data_types t on t.file_type_id=f.file_type_id 
  where dataset_id=14187422;
```
```
/store/relval/CMSSW_12_0_0_pre6/RelValMinBias_14TeV/GEN-SIM/120X_mcRun3_2021_realistic_v4-v1/00000/f6145ee9-113a-487a-ad7f-664fa5c39a26.root	1	EDM
/store/relval/CMSSW_12_0_0_pre6/RelValMinBias_14TeV/GEN-SIM/120X_mcRun3_2021_realistic_v4-v1/00000/fc6ea615-085c-4d4a-8eae-5bf1c3a45078.root	1	EDM
/store/relval/CMSSW_12_0_0_pre6/RelValMinBias_14TeV/GEN-SIM/120X_mcRun3_2021_realistic_v4-v1/00000/aee67840-3908-461b-bf3a-effe38e510bb.root	1	EDM
/store/relval/CMSSW_12_0_0_pre6/RelValMinBias_14TeV/GEN-SIM/120X_mcRun3_2021_realistic_v4-v1/00000/d362fce9-ea34-481a-a896-cd4b996b0f00.root	1	EDM
/store/relval/CMSSW_12_0_0_pre6/RelValMinBias_14TeV/GEN-SIM/120X_mcRun3_2021_realistic_v4-v1/00000/a602c821-a094-4e79-b494-cd4d8c0ac010.root	1	EDM
/store/relval/CMSSW_12_0_0_pre6/RelValMinBias_14TeV/GEN-SIM/120X_mcRun3_2021_realistic_v4-v1/00000/45ffacf4-9863-478d-af36-1f5624f08ecf.root	1	EDM
/store/relval/CMSSW_12_0_0_pre6/RelValMinBias_14TeV/GEN-SIM/120X_mcRun3_2021_realistic_v4-v1/00000/7475edf8-1e60-4cd0-a57c-4ef6611aa6e3.root	1	EDM
```

**Comment by amaltaro** [comment]
Thanks for this feedback, Yuyi! That is probably the reason why many of the WMCore templates suddenly do not work anymore! I thought the only change that they were planning to do was involving the phys03 db. Well, I'm going to follow this with the HTTP/Valentin team, likely on Monday though. Thanks again!

**Comment by yuyiguo** [comment]
Alan,
I am sorry that WMCore templates did not work suddenly.
CMS_DBS3_int_global_owner@int2r is our db for the int server/cmsweb-testbed .  cms_dbs3_k8s_global_owner@cmsr was for k8s integration test.  They should not be mixed to use. I gave Valentin cms_dbs3_k8s_global_owner for the go test since  we are done with k8s testing and this DB has more data than int one.

I will be in the woods for camping. I may not have signals and have to get back to you after a week if you need something from DBS.

**Comment by muhammadimranfarooqi** [comment]
@yuyiguo @amaltaro 

The cmsweb-testbed points to DBS from kubernetes cluster. In k8s, we use `cms_dbs3_k8s_global_owner@cmsr` .

**Comment by amaltaro** [comment]
> The cmsweb-testbed points to DBS from kubernetes cluster. In k8s, we use cms_dbs3_k8s_global_owner@cmsr .

since when? Are DBS cmsweb-testbed requests always routed to the k8s cluster? Or we have a mix of instances (using a mix of database instances as well)?

**Comment by muhammadimranfarooqi** [comment]
@amaltaro 

In the past few months ago, don't remember exact timeframe, I tested mixed approach pointing to both VM testbed and K8s DBS instances simultaneously. This was done only for testing and rolled back. and yes

**Comment by amaltaro** [comment]
@muhammadimranfarooqi thanks for your reply!
Is it correct to assume that we are not moving back to the `CMS_DBS3_int_global_owner` db instance then and from now on only the kubernetes one will be used?

**Comment by muhammadimranfarooqi** [comment]
> @muhammadimranfarooqi thanks for your reply! Is it correct to assume that we are not moving back to the `CMS_DBS3_int_global_owner` db instance then and from now on only the kubernetes one will be used?

Yes, for cmsweb-testbed.
