### ISSUE TITLE
Python3 dbs3-client (>=3.17.3) not backwards compatible

### ISSUE THREAD

**Issue by amaltaro** [dmwm/DBSClient#17]
Yuyi, I finally managed to build dbs3-client and dbs3-pycurl from PyPi, provided in this PR:
https://github.com/cms-sw/cmsdist/pull/7360

and deployed it together with a test WMAgent package. There are two blocker issues that I'd like to report here.
1) this new client breaks compatibility with previous versions and it will require a refactoring on all applications that want to upgrade to the latest dbs3-client package. See [1]
2) there is a new unfulfilled dependency on `RestClient` package. I expected it to come from `dbs3-pycurl` package, but it doesn't seem to be the case. See [2] 

The dbs3-pycurl package doesn't seem to ship any library, looking at the wmagent installation area:
```
cmst1@vocms0261:/data/srv/wmagent/current $ ls sw.amaltaro/slc7_amd64_gcc630/cms/py3-dbs3-pycurl/3.17.3/lib/python3.8/site-packages/
dbs-3.4.4-py3.8.egg-info
cmst1@vocms0261:/data/srv/wmagent/current $ ls sw.amaltaro/slc7_amd64_gcc630/cms/py3-dbs3-pycurl/3.17.3/lib/python3.8/site-packages/dbs-3.4.4-py3.8.egg-info/
dependency_links.txt  installed-files.txt  PKG-INFO  SOURCES.txt  top_level.txt
```

Please let me know if you need any further information.

[1]
```
>>> from dbs.apis.dbsClient import DbsApi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'dbs'
### reason is, the top level package has been renamed to `dbsClient`
```

[2]
```
>>> from dbsClient.apis.dbsClient import DbsApi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/srv/wmagent/v1.5.4.pre2-comp/sw.amaltaro/slc7_amd64_gcc630/cms/py3-dbs3-client/3.17.3/lib/python3.8/site-packages/dbsClient/apis/dbsClient.py", line 2, in <module>
    from RestClient.ErrorHandling.RestClientExceptions import HTTPError
ModuleNotFoundError: No module named 'RestClient'
### note that the import has been fixed now, which makes it fail somewhere else
```

**Comment by yuyiguo** [comment]
@amaltaro I had no problem to build and test this new release with both  dbs3-client and dbs3-pycurl  for pypi. The problem is with the libcurl to work with voms.  Let me apply the changes I made to the test code to here.   As soon as I can make the voms work, I will let you know.

**Comment by amaltaro** [comment]
@yuyiguo I guess if you could reach out to those using dbs3-client at the moment (likely WMCore, CRAB, Unified, McM/Stats/PmP) and ask whether this breaking change is acceptable for them, then keeping `dbsClient` directory/package is an option.

If you want to avoid this extra effort though, then I would suggest to change that directory name back to `dbs`, such that a dbs3-client upgrade doesn't break clients using it.

**Comment by yuyiguo** [comment]
@amaltaro 
Thank you for your messages. Considering there are a list of individual users besides WMCore, Crab and the other projects, I decided to  use `from dbs.apis.dbsClient import DbsApi` . So no changes needed from the users' side,

I tested this py3 client with DBS unit tests and they looked good. There were some updates needed on the unit tests themselves ,  but the [dbs3-client](https://pypi.org/project/dbs3-client/3.17.5/) and [dbs3-pycurl ](https://pypi.org/project/dbs3-pycurl/#files)all work to me. 

Can you give  a try ?  Here are quick installations:
pip install dbs3-pycurl==3.17.4
pip install dbs3-client==3.17.5

For details, please see project [wiki page](https://github.com/dmwm/DBSClient/wiki).

**Comment by amaltaro** [comment]
I actually built WMCore central services with those releases you mentioned above. I should have some results by tomorrow ;)

**Comment by amaltaro** [comment]
@yuyiguo here is the first problem with dbs3-client 3.17.5:
```
  File "/data/srv/HG2110b-comp7/sw.amaltaro/slc7_amd64_gcc630/cms/py3-dbs3-client/3.17.5/lib/python3.8/site-packages/dbs/apis/dbsClient.py", line 1, in <module>
    from dbsClient.exceptions.dbsClientException import dbsClientException
ModuleNotFoundError: No module named 'dbsClient'
```

fixing that import to:
```
from dbs.exceptions.dbsClientException import dbsClientException
```
allows services to start. I'm going to test whether the client calls work now.

**Comment by amaltaro** [comment]
@yuyiguo I'm planning to integrate another spec into the WMCore stack. So if you can provide a new tag by Monday, I could do both tests in parallel. Thanks

**Comment by yuyiguo** [comment]
@amaltaro  I created 3.17.6.

**Comment by amaltaro** [comment]
Some basic tests suggest that this is now working fine with `3.17.6` (and `3.17.4` for dbs3-pycurl), thanks Yuyi!
@yuyiguo I think we can now close this ticket. If you think I'm missing anything, please reopen it.
