### ISSUE TITLE
Adjust DBS Client to aggregate data from dbs2go server

### ISSUE THREAD

**Issue by vkuznet** [dmwm/DBSClient#19]
Upon discussion within DMWM we agreed to adjust DBS Client to aggregate data from `dbs2go` server. This issue is a placeholder with requirements, which are the following:
- add aggregation functionality to sub-set of DBS APIs, e.g. `runs`, etc., see full discussion in https://github.com/dmwm/WMCore/issues/10841
- add additional option to perform aggregation, and make it true by default. This will allow later to change the default to false (i.e. do not perform aggregation) and make it transparent to upstream users of DBS client
- ensure that DBS Client will work transparently with existing Python server and new `dbs2go` one
- once all changes will be place make new release and install it with CMS software stack (WMA, CRAB, etc.) such that DBS Client will be ready for migration from Python to Go based DBS server

@klannon , @amaltaro , @yuyiguo this is a placeholder ticket to list set of requirements we discussed will be required to complete migration to Go based DBS server. Please review and add/change necessary items.

I plan to do all the necessary work for this issue.

**Comment by klannon** [comment]
This looks good to me.

**Comment by yuyiguo** [comment]
Done.
