### ISSUE TITLE
Mixed Tabs and Spaces

### ISSUE THREAD

**Issue by klannon** [dmwm/DBSClient#23]
I noticed in #22, there was a comment from @vkuznet about mixed tabs and spaces.  This comment has arisen in some past discussions about DBS.  I tried to understand how serious an issue this is by cloning the repository locally and looking for tabs.  Here's what I found:
```
klannon@kplmac DBSClient % find . -name "*.py" -exec grep -lH  '\t' {} \;
./tests/dbsclient_t/unittests/DBSClientReader_t.py
./tests/dbsclient_t/utils/DBSDataProvider.py
./utils/dbs2Todbs3DatasetMigrate.py
./utils/DataOpsScripts/DBS3SetFileStatus.py
./utils/DataOpsScripts/EventsPerDay.py
./utils/insert_block_migration_requests-MINIAOD.py
./utils/listFileinBlock.py
./utils/readTestLogs.py
./utils/run_test.py
./src/python/dbs/apis/dbsClient.py
```

I opened some of these files in `emacs` (yes, I know; I'm ancient) and indeed, for most of the ones I checked, the files are indented mostly with spaces, but a few lines are indented with tabs.  There were a couple of files that I checked which seemed consistently tab-indented.

I know that mixing tabs and spaces is a really bad practice, and I would like it if we could fix this problem.  I considered trying to fix it myself, and was about halfway through just simple-mindedly doing a find/replace on `tab` -> `spaces` when I noticed that sometimes when I did that (at least in `emacs`) it actually changed the indentation.  At this point, I gave up because unfortunately, I don't have time to read every single line that needs to have spaces swapped for tabs, understand what it's doing, and then verify that I haven't changed the logic of the code when I do the replacement.

At the end of the day, there are just 10 files with this problem.  @vkuznet and @yuyiguo, could you please work together to repair these 10 files?  I would really like the two of you to do this without fighting about whose fault it is that this has happened.  For the one case that I tracked carefully, the file was imported into the repository in a mixed space-tab state.  The DBS code is really old and has had dozens (if not more) developers contributing over who knows how many years.  Let's just agree that neither of you is at fault for the state that this code is in.  OK?

Note: some of the files with tabs look like they are both very old and possibly completely unnecessary now.  (E.g. `dbs2Todbs3DatasetMigrate.py`  Surely, we don't need a script for migrating DBS2 to DBS3 anymore, right?)  For the case of files like that, I would recommend just completely dropping the file rather than trying to fix it.  I'd say the same reasoning might apply to anything in `DataOpsScripts` or `utils` that looks like it was created to solve a one-off problem and then never used again.  We have all these files in the original DBS repo, so I don't think we need to worry about preserving them here.  Of course, if there's any uncertainty about whether the file might be needed, especially for the data ops team, then certainly it should be retained.  I'm just pointing out that if we're doing some house cleaning, throwing out code that's no longer used can make it easier to maintain what remains!

**Comment by yuyiguo** [comment]
covered by ci/cd.
