### ISSUE TITLE
Set up CI for this Repo

### ISSUE THREAD

**Issue by klannon** [dmwm/DBSClient#24]
I didn't realize there was no CI for this repo.  I think it would be good to set something up that would do some code style checks (that would catch any new tab/spaces inconsistencies) and also run the unit tests for any PRs.  @yuyiguo or @vkuznet, would one of you like to volunteer to set this up?  It doesn't have to be super heavy weight.  I think just something that covers the basics setup with GH actions would be great!

**Comment by yuyiguo** [comment]
@vkuznet @amaltaro 
I need to use password in order to upload to pypi. What password should I use in CI/CD? How it is stored?

**Comment by yuyiguo** [comment]
covered by two PRs.
